// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: v1.proto

#include "v1.pb.h"
#include "v1.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace v1 {

static const char* V1Service_method_names[] = {
  "/v1.V1Service/HandleRequest",
};

std::unique_ptr< V1Service::Stub> V1Service::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< V1Service::Stub> stub(new V1Service::Stub(channel, options));
  return stub;
}

V1Service::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_HandleRequest_(V1Service_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status V1Service::Stub::HandleRequest(::grpc::ClientContext* context, const ::v1::Request& request, ::v1::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::v1::Request, ::v1::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HandleRequest_, context, request, response);
}

void V1Service::Stub::async::HandleRequest(::grpc::ClientContext* context, const ::v1::Request* request, ::v1::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::v1::Request, ::v1::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleRequest_, context, request, response, std::move(f));
}

void V1Service::Stub::async::HandleRequest(::grpc::ClientContext* context, const ::v1::Request* request, ::v1::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::v1::Response>* V1Service::Stub::PrepareAsyncHandleRequestRaw(::grpc::ClientContext* context, const ::v1::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::v1::Response, ::v1::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HandleRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::v1::Response>* V1Service::Stub::AsyncHandleRequestRaw(::grpc::ClientContext* context, const ::v1::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandleRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

V1Service::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      V1Service_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< V1Service::Service, ::v1::Request, ::v1::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](V1Service::Service* service,
             ::grpc::ServerContext* ctx,
             const ::v1::Request* req,
             ::v1::Response* resp) {
               return service->HandleRequest(ctx, req, resp);
             }, this)));
}

V1Service::Service::~Service() {
}

::grpc::Status V1Service::Service::HandleRequest(::grpc::ServerContext* context, const ::v1::Request* request, ::v1::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace v1

